app:
  brs-base-url: 
  database-access-type: jdbc
  cron: 0 1 * * ?

spring:
  liquibase:
    changelog: migrations/master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/schedule
    username: mystery
    password: helpmepls

springdoc:
  swagger-ui:
    path: /swagger-ui
